* good issues:
** https://www.huffpost.com/entry/andrew-ng_n_7267682
   But innovation or creativity is a strategic skill where every day you wake up 
   and it’s a totally unique context that no one’s ever been in, and you need to
    make good decisions in your completely unique environment. So as far as I can 
   tell, the only was we know way to teach strategic skills is by example, by seeing 
   tons of examples. The human brain, when you see enough examples, learns to internalize 
   those rules and guidelines for making good strategic decisions.
   
   But what is your best "flight simulator"? the answer is to embrace tons of examples!!!

   <<zero to one>>
   <<cross the chasm>>
   <<the learn startup>>
   <<talking to humans>>
   <<rocket surgery made easy>>
   <<the hard thing about hard thing>>
   <<so good they could not ignore you>>

   When I talk to researchers, when I talk to people wanting to engage in entrepreneurship, 
   I tell them that if you read research papers consistently, if you seriously study half a
    dozen papers a week and you do that for two years, after those two years you will have 
   learned a lot. This is a fantastic investment in your own long term development. 

   Chances are what you learned studying all Saturday won’t make you that much better at your 
   job the following Monday. There are very few, almost no short-term rewards for these things. 
   But it’s a fantastic long-term investment.
   [念念不忘，终有回响。那些不会给你instant gratification的好东西，终会发光]

   The challenge that faces us is to find a way to scalably teach people to do non-routine non-repetitive work. 
   Our education system, historically, has not been good at doing that at scale. The top universities are good 
   at doing that for a relatively modest fraction of the population. But a lot of our population ends up doing 
   work that is important but also routine and repetitive. That’s a challenge that faces our educational system.
   [为工业化时代服务的教育体系，似乎还不适合即将到来的创新时代]
